/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  skill: [
    'skill/introduction',
    {
      label: 'OpenLinker_NUC980',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/OpenLinker_NUC980/pinia',
      ],
    },
    {
      label: '开发板配件',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/开发板配件/3.5寸LCD+电容触摸',
        'skill/开发板配件/5寸LCD+电容触摸',
      ],
    },    
    /*
    {
      label: 'React',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/react',
        },
      ],
    },
    {
      label: 'Web',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/web',
        },
      ],
    },
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: ['skill/css/tailwind-css-usage', 'skill/css/func-and-useful-css-tips'],
    },
    {
      label: 'Go',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/go/go-environment-install',
        'skill/go/go-json-usage',
        'skill/go/go-send-http-request',
        'skill/go/go-call-js',
        'skill/go/go-concurrent',
        'skill/go/try-gin-framework'
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/algorithm',
        },
      ],
    },
    {
      label: '逆向',
      type: 'category',
      link: {
        title: '逆向笔记',
        description: 'Web逆向与安卓逆向笔记',
        type: 'generated-index',
        keywords: ['reverse', 'web', 'android', 'frida'],
      },
      items: [
        {
          label: '安卓',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/android',
            },
          ],
        },
        {
          label: 'Web',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/web',
            },
          ],
        },
        {
          label: '密码学',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/crypto',
            },
          ],
        },
      ],
    },
    {
      label: 'Docker',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/docker',
        },
      ],
    },
    {
      label: '数据库',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
    */
  ],
  tools: [
    'tools/introduction',
    {
      label: '管理类',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'tools/管理类/管理类图书',
      ],
    },    
    {
      label: '开发类',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'tools/开发类/软件开发图书',
        'tools/开发类/硬件开发图书',        
      ],
    },      
  ]
}

module.exports = sidebars
